### ISSUE TITLE
Use `awesome_bot` to validate links

### ISSUE THREAD

**Issue by erictleung** [danielecook/Awesome-Bioinformatics#27]
What do you think about adding a Travis CI script for `awesome_bot` to validate links on the page in case some go old and stop working?

Source: https://github.com/dkhamsing/awesome_bot

You just need to make a `.travis.yml` file with the following:

``` yml
language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot README.md
notifications:
  email: false
```

Here are some other options you can use while checking links

```
Usage: awesome_bot [file or files]
       awesome_bot [options]
    -f, --files [files]              Comma separated files to check
    -a, --allow [errors]             Status code errors to allow
        --allow-dupe                 Duplicate URLs are allowed
        --allow-ssl                  SSL errors are allowed
        --allow-redirect             Redirected URLs are allowed
        --allow-timeout              URLs that time out are allowed
    -t, --set-timeout [seconds]      Set connection timeout
    -w, --white-list [urls]          Comma separated URLs to white list
```
